apiVersion: v1
kind: ConfigMap
metadata:
  name: config-command-handler
data:
  {{- $commandHandlerPath := include "evented-command-handler.configFilePath" .}}
  {{ base $commandHandlerPath }}: {{- tpl (toYaml .Values.command_handler.configuration) . | indent 2}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-business-logic
data:
  {{- $businessLogicPath := include "evented-business-logic.configFilePath" .}}
  {{ base $businessLogicPath }}: {{- tpl (toYaml .Values.business_logic.configuration) . | indent 2}}

