apiVersion: v1
kind: ConfigMap
metadata:
  name: config-command-handler
data:
  keys: |
    #YAML 1.2
    ---
    business:
      url: localhost:{{ include "evented-command-handler.business-logic-port" . }}

    port:  {{ include "evented-command-handler.coordinator-port" . }}
    domain: {{ .Values.domain }}

    snapshots:
      kind: memory
      mongodb:
        url: mongodb://evented-mongodb.default.svc.cluster.local:27017
        name: commandHandlerSnapshots
        collection: snapshots

    transport:
      kind: noop
      rabbitmq:
        url: amqp://test:test@rabbitmq.default.svc:5672
        exchange: evented

    events:
      kind: memory
      mongodb:
        url: mongodb://evented-mongodb.default.svc.cluster.local:27017
        name: commandHandlerEvents
        collection: events

    proof: pudding