apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evented-command-handler.fullname" . }}
  labels:
    {{- include "evented-command-handler.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "evented-command-handler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "evented-command-handler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "evented-command-handler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: coordinator
          image: {{ .Values.command_handler.image.repository }}:{{ .Values.command_handler.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.command_handler.image.pullPolicy }}
          ports:
            - name: evtd
              containerPort: {{ include "evented-command-handler.coordinator-port" . }}
              protocol: TCP
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=localhost:{{ include "evented-command-handler.coordinator-port" .}}" ]
{{/*            grpc:*/}}
{{/*              port: {{ include "evented-command-handler.coordinator-port" . }}*/}}
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=localhost:{{ include "evented-command-handler.coordinator-port" .}}" ]
{{/*            grpc:*/}}
{{/*              port: {{ include "evented-command-handler.coordinator-port" . }}*/}}
          resources:
            {{- toYaml .Values.command_handler.resources | nindent 12 }}
          env:
            {{- toYaml .Values.command_handler.env | nindent 12 }}
            - name: CONFIG_MGMT_TYPE
              value: file
            - name: CONFIG_PATH
              value: /etc/evented/command-handler.yaml
          volumeMounts:
            - mountPath: /etc/evented/command-handler.yaml
              name: config-command-handler

        - name: business-logic
          securityContext: {{- toYaml .Values.business_logic.securityContext | nindent 12 }}
          image: "{{ .Values.business_logic.image.repository }}:{{ .Values.business_logic.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.business_logic.image.pullPolicy }}
          ports:
            - name: business
              containerPort: {{ include "evented-command-handler.business-logic-port" . }}
              protocol: TCP
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=localhost:{{ include "evented-command-handler.business-logic-port" .}}" ]
{{/*            grpc:*/}}
{{/*              port: {{include "evented-command-handler.business-logic-port" .}}*/}}
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=localhost:{{ include "evented-command-handler.business-logic-port" .}}" ]
{{/*            grpc:*/}}
{{/*              port: {{include "evented-command-handler.business-logic-port" .}}*/}}
          env:
            {{- toYaml .Values.business_logic.env  | nindent 12}}
            - name: CONFIG_MGMT_TYPE
              value: file
            - name: CONFIG_PATH
              value: /etc/evented/business-logic.yaml
            - name: APP_NAME
              value: todo
          resources:
            {{- toYaml .Values.business_logic.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/evented/business-logic.yaml
              name: config-business-logic
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
