apiVersion: v1
kind: Service
metadata:
  name: {{ include "commandHandler.fullname" . }}
  labels:
    {{- include "commandHandler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1747
      protocol: TCP
      name: evented
  selector:
    {{- include "commandHandler.selectorLabels" . | nindent 4 }}

