apiVersion: v1
kind: Service
metadata:
  name: {{ include "evented-query-handler.fullname" . }}
  labels:
    {{- include "evented-query-handler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: grpc-evented-query-handler
  selector:
    {{- include "evented-query-handler.selectorLabels" . | nindent 4 }}
