selectorLabels:
  selectorLabel: "selectorLabel"

labels:
  label: "label"

domain: "todo"

command_handler:
  port: 1313 #ASCII "CQRS" +1000 to get out of priv ports
  image:
    repository: evented-command-handler
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  securityContext: { }
  resources: { }
  env:
    - name: CONFIG_MGMT_TYPE
      value: file
    - name: CONFIG_TYPE
      value: yaml
    - name: CONFIG_FILE_PATH
      value: /evented/etc/command-handler.yaml
    - name: APP_NAME
      value: command-handler


business_logic:
  port: 1737 #ASCII "evented" + 1000 to get out of priv ports
  image:
    repository: todo
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  securityContext: { }
  resources: { }
  env:
    - name: CONFIG_MGMT_TYPE
      value: file
    #- name: CONSUL_HOST
    #  value: consul-server.default.svc.cluster.local:8500
    - name: CONFIG_TYPE
      value: yaml
    #- name: CONSUL_KEY
    #  value: evented-sample-business-logic
    - name: APP_NAME
      value: sample-business-logic
    - name: CONFIG_FILE_PATH
      value: /evented/etc/command-handler.yaml


imagePullSecrets: [ ]

replicaCount: 1

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "saName"

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

service:
  type: LoadBalancer
  port: 1313

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }
