FROM evented-base AS app-build
COPY --from=evented-base /root/.cache /root/.cache
RUN cd /src && CGO_ENABLED=0 go build -gcflags="all=-N -l" -o app ./applications/commandHandler

FROM scratch-foundation AS final
ARG VERSION
ENV VERSION $VER
EXPOSE 40000
COPY --from=app-build /src/app /bin/
COPY --from=app-build /go/bin/dlv /bin/

CMD ["/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/bin/app"]
