apiVersion: v1
kind: Service
metadata:
  name: {{ include "evented-command-handler.fullname" . }}
  labels:
    {{- include "evented-command-handler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: evtd
      protocol: TCP
      name: evtd
  selector:
    {{- include "evented-command-handler.selectorLabels" . | nindent 4 }}
