apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    evented: sample-business-logic
  name: evented-sample-business-logic
spec:
  selector:
    matchLabels:
      evented: sample-business-logic
  template:
    metadata:
      labels:
        evented: sample-business-logic
    spec:
      containers:
        - name: evented-sample-business-logic
          image: evented-sample-business-logic
          imagePullPolicy: Never
          env:
            - name: CONFIG_MGMT_TYPE
              value: consul
            - name: CONSUL_HOST
              value: consul-server.default.svc.cluster.local:8500
            - name: CONSUL_CONFIG_TYPE
              value: yaml
            - name: CONSUL_KEY
              value: evented-sample-business-logic
            - name: APP_NAME
              value: sample-business-logic
---
apiVersion: v1
kind: Service
metadata:
  labels:
    evented: sample-business-logic
  name: evented-sample-business-logic
spec:
  type: NodePort
  ports:
    - name: grpc-evented-business
      port: 1739
      nodePort: 30001
    - port: 40000
      name: debug
      nodePort: 32001
  selector:
    evented: sample-business-logic

