# Default values for evented-projector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

coordinator:
  #The projector coordinator is the sidecar that coordinates and drives the projector logic.
  image:
    repository: evented-projector
    pullPolicy: Never
    tag: "latest"
  securityContext: { }
  resources: { }
  env:
    - name: CONFIG_MGMT_TYPE
      value: consul
    - name: CONSUL_HOST
      value: consul-server.default.svc.cluster.local:8500
    - name: CONSUL_CONFIG_TYPE
      value: yaml
    - name: CONSUL_KEY
      value: evented-projector
    - name: APP_NAME
      value: evented-projector


projector:
  image:
    repository: evented-sample-projector
    pullPolicy: Never
    tag: "latest"
  resources: { }
  securityContext: { }
  env:
    - name: CONFIG_MGMT_TYPE
      value: consul
    - name: CONSUL_HOST
      value: consul-server.default.svc.cluster.local:8500
    - name: CONSUL_CONFIG_TYPE
      value: yaml
    - name: CONSUL_KEY
      value: evented-sample-projector
    - name: APP_NAME
      value: evented-sample-projector


imagePullSecrets: [ ]

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

service:
  type: ClusterIP
  port: 1315

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }
