# values.yaml
global:
  name: consul
connectInject:
  enabled: false
syncCatalog:
  enabled: true
ui:
  service:
    type: 'LoadBalancer'
server:
  replicas: 1
  bootstrapExpect: 1 #must be <= server.replicas
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname