# Do not use, check https://mfarache.github.io/mfarache/Deploying-Micronaut-Kubernetes/
# TODO: fix this

apiVersion: batch/v1
kind: Job
metadata:
  name: dns
spec:
  template:
    spec:
      containers:
        - name: dns
          image: anubhavmishra/tiny-tools
          command: [ 'dig', 'consul.service.consul' ]
      restartPolicy: Never
  backoffLimit: 4