apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    evented: coordinator-projector-amqp
  name: evented-coordinator-projector-amqp
spec:
  selector:
    matchLabels:
      evented: coordinator-projector-amqp
  template:
    metadata:
      labels:
        evented: coordinator-projector-amqp
    spec:
      containers:
        - name: evented-coordinator-sample-projector-amqp
          image: evented-coordinator-projector-amqp
          imagePullPolicy: Never
          env:
            - name: CONFIG_MGMT_TYPE
              value: consul
            - name: CONSUL_HOST
              value: consul-server.default.svc.cluster.local:8500
            - name: CONSUL_CONFIG_TYPE
              value: yaml
            - name: CONSUL_KEY
              value: evented-coordinator-sample-projector-amqp
            - name: APP_NAME
              value: evented-coordinator-sample-projector-amqp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    evented: coordinator-projector-amqp
  name: evented-coordinator-projector-amqp
spec:
  type: NodePort
  ports:
    - port: 40000
      name: debug
      nodePort: 32003
  selector:
    evented: coordinator-projector-amqp

