apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-business.fullname" . }}
  labels:
    {{- include "sample-business.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1747
      protocol: TCP
      name: evented
  selector:
    {{- include "sample-business.selectorLabels" . | nindent 4 }}
