apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    evented: amqp-projector
  name: evented-amqp-projector
spec:
  selector:
    matchLabels:
      evented: amqp-projector
  template:
    metadata:
      labels:
        evented: amqp-projector
    spec:
      containers:
        - name: evented-amqp-projector
          image: evented-amqp-projector
          imagePullPolicy: Never
          env:
            - name: CONFIG_MGMT_TYPE
              value: consul
            - name: CONSUL_HOST
              value: consul-server.default.svc.cluster.local:8500
            - name: CONSUL_CONFIG_TYPE
              value: yaml
            - name: CONSUL_KEY
              value: evented-ampq-projector
            - name: APP_NAME
              value: evented-amqp-projector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    evented: amqp-projector
  name: evented-amqp-projector
spec:
  type: NodePort
  ports:
    - port: 40000
      name: debug
      nodePort: 32003
  selector:
    evented: amqp-projector

