ARG BUILD_IMAGE
FROM ${BUILD_IMAGE} AS app-build
COPY --from=evented-base /root/.cache /root/.cache
ARG VERSION
ARG BUILD_TIME
RUN cd /src && CGO_ENABLED=0 go build -o /app/app -ldflags "-X github.com/benjaminabbitt/evented/support.Version=${VERSION} -X github.com/benjaminabbitt/evented/support.BuildTime=${BUILD_TIME}" ./applications/command/command-handler

ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE} AS final
COPY --from=app-build /app/app /app/

CMD ["/app/app"]
